// CryptoPortfolioTracker/frontend-Main-React/src/Dashboard.tsx
import { AddAsset, GetAsset, DeleteAsset } from "./services/Dashboard.services";
import { useState } from "react";

import "./Dashboard.css";

function Dashboard(data: any) {
  const [token, setToken] = useState("");
  const [quantity, setQuantity] = useState("");
  const [error_messsage, setErrorMesssage] = useState("");
  const [asset_button_value, setAssetButtonValue] = useState("Add Asset");
  const [asset_button_id, setAssetButtonID] = useState("dashboard_add_button");
  const [dataSource, setDataSource] = useState(data.data);

  document.getElementById("logout_link").style.display = "block";

  async function handleAddAsset(event: any) {
    event.preventDefault();
    if (
      token === null ||
      token === "" ||
      quantity === null ||
      quantity === ""
    ) {
      setErrorMesssage ("Error: Please fill all the details");
    } else {
      await AddAsset({
        username: data.username,
        token: token,
        quantity: +quantity,
      });
      setToken("");
      setQuantity("");
      setDataSource(await GetAsset(data.username));
    }
  }

  async function handleDeleteAsset(event: any, token: string, quantity: number, row: number) {
    event.preventDefault();
    if(await DeleteAsset(data.username, token, quantity)){
      const updatedUsers = dataSource.filter((dataSource: any, idx: number) => idx !== row);
      setDataSource( updatedUsers );
    }
  }

  async function handleEditAsset(event: any, token: string, quantity: number) {
    event.preventDefault();
    setToken(token);
    setQuantity(quantity.toString());
    setAssetButtonValue("Save Asset");   
    setAssetButtonID("dashboard_save_button");
  }

  return (
    <div id="Dashboard">
      <h1 id="dashboard_heading">Dashboard</h1>
      <br />
      <table id="assets_table">
        <thead>
          <tr>
            <th className="table_heading">Token</th>
            <th className="table_heading">Qty. Owned</th>
            <th className="table_heading">Price</th>
            <th className="table_heading">Total Value</th>
            <th className="table_heading">Allocation</th>
            <th className="table_heading">Actions</th>
          </tr>
        </thead>
        <tbody id="table_body">
          {dataSource.map((item: any, row: number) => (
            <tr key={row}>
              <td className="table_data">{item.token}</td>
              <td className="table_data">{item.quantity}</td>
              <td className="table_data">${item.price}</td>
              <td className="table_data">${item.totalValue}</td>
              <td className="table_data">{item.allocation}%</td>
              <td className="table_data">
                <button className="delete_button" onClick={(event)=>{handleDeleteAsset(event, item.token, +item.quantity, row)}}>delete</button>
                <button className="edit_button" onClick={(event)=>{handleEditAsset(event, item.token, +item.quantity)}}>edit</button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      <br />
      <br />
      <form id="add_asset_form" onSubmit={handleAddAsset}>
        <label id="token_label" htmlFor="dashboard_token">
          Token:{" "}
        </label>
        <input
          id="dashboard_token"
          type="text"
          onChange={(event) => (setToken(event.target.value))}
          value={token}
        />
        <label id="quantity_label" htmlFor="dashboard_quantity">
          Quantity:{" "}
        </label>
        <input
          id="dashboard_quantity"
          type="text"
          onChange={(event) => (setQuantity(event.target.value))}
          value={quantity}
        />
        <div id="asset_button_div">
          <button id={asset_button_id} type="submit">
            {asset_button_value}
          </button>
        </div>
      </form>
      <br />
      <label id="add_asset_error">{error_messsage}</label>
    </div>
  );
}

export default Dashboard;

// CryptoPortfolioTracker/frontend-Main-Angular/src/app/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder } from '@angular/forms';

import { Asset } from '../models/asset.model';
import { DashboardServices } from '../services/dashboard.service';
import { AppComponent } from '../app.component'

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css'],
})
export class DashboardComponent implements OnInit {
  assetMessage = '';
  cyptoArray: any;
  addEditButton = "Add Asset";
  addEditButtonID = "dashboard_add_button";

  addCryptoForm = this.formBuilder.group({
    dashboard_token: null,
    dashboard_quantity: null
  });

  constructor(
    private readonly formBuilder: FormBuilder,
    private readonly dashboardServices: DashboardServices,
    private readonly appComponent: AppComponent
  ) {}

  ngOnInit(): void {
    this.appComponent.edited = true;
    this.populateTableData();
  }

  addCrypto(): void {
    const tokenName = this.addCryptoForm.value.dashboard_token;
    const tokenQuantity = +this.addCryptoForm.value.dashboard_quantity;

    if (tokenName !== null && tokenQuantity !== null && tokenName !== '') {
      const asset = new Asset(tokenName, tokenQuantity);

      this.dashboardServices.addAsset(asset).subscribe(
        (response) => {
          if (response.ok) {
            this.cyptoArray.push({ token: tokenName, quantity: tokenQuantity });
            this.assetMessage = 'Asset added succefully';
          }
        },
        (error) => {
          console.log(error);
          this.assetMessage = 'Error: An error has occurred ';
        }
      );
    } else {
      this.assetMessage = 'Error: Please fill all the details';
    }
  }

  deleteCrypto(rowIdx: number, tokenName:string, tokenQuantity: number): void {

    const asset = new Asset(tokenName, +tokenQuantity);

    this.dashboardServices.deleteAsset(asset).subscribe(
      (response) => {
        if (response.ok) {
          this.cyptoArray.splice(rowIdx, 1);
        }
      },
      (error) => {
        console.log(error);
      }
    );
  }

  editCrypto(rowIdx: number, tokenNameT:string, tokenQuantityT: number): void {

    this.addCryptoForm.controls['dashboard_token'].setValue(tokenNameT);
    this.addCryptoForm.controls['dashboard_quantity'].setValue(tokenQuantityT);

    this.addEditButton = 'Save Asset';
    this.addEditButtonID = 'dashboard_save_button';

  }

  populateTableData(): void {
    this.dashboardServices.getAssets().subscribe(
      (response) => {
        if (response.ok) {
          this.cyptoArray = response.body;
        }
      },
      (error) => {
        console.log(error);
      }
    );
  }
}

<h1 id="dashboard_heading">Dashboard</h1>
<table id="assets_table" >
  <caption>
    Assets
  </caption>
  <thead>
    <tr>
      <th class="table_heading">Token</th>
      <th class="table_heading">Qty. Owned</th>
      <th class="table_heading">Price</th>
      <th class="table_heading">Total Value</th>
      <th class="table_heading">Allocation</th>
      <th class="table_heading">Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let asset of cyptoArray; let idx = index">
      <td class="table_data">{{asset.token}}</td>
      <td class="table_data">{{asset.quantity}}</td>
      <td class="table_data">${{asset.price}}</td>
      <td class="table_data">${{asset.totalValue}}</td>
      <td class="table_data">{{asset.allocation}}%</td>
      <td>
        <button class="delete_button" (click)="deleteCrypto(idx, asset.token, asset.quantity)">delete</button>
        <button class="edit_button" (click)="editCrypto(idx, asset.token, asset.quantity)">edit</button>
      </td>
   </tr>
  </tbody>
</table><br><br>
<div>
  <form [formGroup]="addCryptoForm" (ngSubmit)="addCrypto()">
    <label for="dashboard_token">Token: </label>
    <input id="dashboard_token" type="text" formControlName="dashboard_token"/>
    <label for="dashboard_quantity">Quantity: </label>
    <input id="dashboard_quantity" type="text" formControlName="dashboard_quantity"/>
    <button id="{{addEditButtonID}}" type="submit" >{{addEditButton}}</button><br>
    <label id="add_asset_error">{{ assetMessage }}</label>
  </form>
</div>
